# spring settings
spring.profiles.active: dev

security.oauth2.resource.filter-order: 3

server:
  port: 9000
  use-forward-headers: true

logging:
  level:
    ROOT: INFO
    org.springframework.security: INFO
    org.springframework.security.jwt.sample: INFO
  file: ./build/vending-back-machine-application.log

mail:
  senderEmail: todo@vbm-todo.com
  dataUploadError:
    recipientsEmail: vyemialyanchyk@gmail.com
  system.failure.notify: vyemialyanchyk@gmail.com

spring:
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
