package com.vending.back.machine.helper.history;

import org.springframework.stereotype.Component;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * vyemialyanchyk on 1/30/2017.
 */
@Component
@Retention(RetentionPolicy.RUNTIME)
@Target(value={ElementType.METHOD, ElementType.FIELD})
public @interface Trackable {
    /**
     * @return Base table name to be bound to history table. History table generated by adding suffix.
     */
    String table();

    /**
     * @return Where clause used when generating history entry. Should select single row.
     */
    String where();

    String table02() default "";
    String where02() default "";
}
